# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clock_divider_0_0/design_1_clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clock_divider_0_0 || ORIG_REF_NAME==design_1_clock_divider_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clock_divider_1_0/design_1_clock_divider_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clock_divider_1_0 || ORIG_REF_NAME==design_1_clock_divider_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clock_divider_2_0/design_1_clock_divider_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clock_divider_2_0 || ORIG_REF_NAME==design_1_clock_divider_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clock_divider_3_0/design_1_clock_divider_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clock_divider_3_0 || ORIG_REF_NAME==design_1_clock_divider_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pwn_divider_0_1/design_1_pwn_divider_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pwn_divider_0_1 || ORIG_REF_NAME==design_1_pwn_divider_0_1} -quiet] -quiet

# XDC: d:/ashvi/fpga/blinker_pt3/blinker_pt3.gen/sources_1/bd/design_1/design_1_ooc.xdc
